# Generated by Django 5.1.7 on 2026-06-01 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0007_alter_vehiculo_vin'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField(default=django.utils.timezone.now)),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=15)),
                ('numero_boleto', models.CharField(blank=True, max_length=20, null=True)),
                ('ruta_boleto_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, null=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_titular', to=settings.AUTH_USER_MODEL)),
                ('cliente_cotitular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_cotitular', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='sucursales.sucursaltemp')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo_usado_entregado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_compra', to='inventario.vehiculo')),
                ('vehiculo_vendido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_venta', to='inventario.vehiculo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_iniciadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('pagare', 'Pagaré'), ('financiamiento_externo', 'Financiamiento Externo'), ('financiamiento_interno', 'Financiamiento Interno'), ('dolares', 'Dólares')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cotizacion_dolar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='ventas.operacionventa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='operacionventa',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_boleto__isnull', False)), fields=('sucursal', 'numero_boleto'), name='unique_boleto_por_sucursal'),
        ),
        migrations.AddConstraint(
            model_name='operacionventa',
            constraint=models.CheckConstraint(condition=models.Q(('precio_final__gte', 0)), name='check_precio_final_positivo'),
        ),
        migrations.AddConstraint(
            model_name='formapago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='check_monto_forma_pago_positivo'),
        ),
    ]
