# Generated by Django 5.1.7 on 2026-06-01 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_vehiculo_vin'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=15)),
                ('fecha_anticipo', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicado', 'Aplicado'), ('devuelto', 'Devuelto'), ('retenido', 'Retenido')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to=settings.AUTH_USER_MODEL)),
                ('operacion_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos', to='ventas.operacionventa')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to='inventario.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='operacionventa',
            name='anticipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacion_aplicada', to='ventas.anticipo'),
        ),
        migrations.AddConstraint(
            model_name='anticipo',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='check_monto_anticipo_positivo'),
        ),
    ]
