# Generated by Django 5.1.7 on 2026-06-16 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_anticipo_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cheque', 'Cheque'), ('pagare', 'Pagaré')], max_length=10)),
                ('numero_documento', models.CharField(max_length=20)),
                ('banco_emisor', models.CharField(blank=True, max_length=100, null=True)),
                ('titular', models.CharField(blank=True, max_length=150, null=True)),
                ('plazo_dias', models.IntegerField(choices=[(0, '0'), (30, '30'), (60, '60'), (90, '90')], default=0)),
                ('fecha_recepcion', models.DateField()),
                ('fecha_cobro', models.DateField()),
                ('fecha_acreditacion', models.DateField(blank=True, null=True)),
                ('forma_acreditacion', models.CharField(blank=True, choices=[('ventanilla', 'Ventanilla'), ('deposito', 'Depósito')], max_length=15, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes_mora', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('habilitado', 'Habilitado'), ('vencido', 'Vencido'), ('cobrado', 'Cobrado'), ('rechazado', 'Rechazado'), ('en_gestion', 'En Gestión')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anticipo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulo_credito', to='ventas.anticipo')),
                ('documento_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovaciones', to='ventas.titulocredito')),
                ('forma_pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titulo_credito', to='ventas.formapago')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago_real', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pago_con_mora', models.BooleanField(default=False)),
                ('monto_mora_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('forma_cobro', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('pagare', 'Pagaré')], max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_registrados', to=settings.AUTH_USER_MODEL)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_cobro', to='ventas.titulocredito')),
            ],
        ),
        migrations.AddConstraint(
            model_name='titulocredito',
            constraint=models.UniqueConstraint(condition=models.Q(('banco_emisor__isnull', False)), fields=('numero_documento', 'banco_emisor'), name='unique_numero_banco_emisor'),
        ),
        migrations.AddConstraint(
            model_name='titulocredito',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='check_monto_titulo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='registrocobro',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado__gt', 0)), name='check_monto_pagado_positivo'),
        ),
    ]
