# Generated by Django 5.1.7 on 2026-06-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_anticipo_operacionventa_anticipo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operacionventa',
            name='unique_boleto_por_sucursal',
        ),
        migrations.RemoveConstraint(
            model_name='operacionventa',
            name='check_precio_final_positivo',
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
