# Generated by Django 5.1.7 on 2026-06-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_titulocredito_registrocobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulocredito',
            name='fecha_vencimiento_manual',
            field=models.DateField(blank=True, help_text='Solo para pagarés. Fecha de vencimiento acordada, independiente de plazos fijos.', null=True),
        ),
        migrations.AlterField(
            model_name='registrocobro',
            name='forma_cobro',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='titulocredito',
            name='fecha_cobro',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='titulocredito',
            name='plazo_dias',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (30, '30'), (60, '60'), (90, '90')], null=True),
        ),
    ]
