# Generated by Django 5.1.7 on 2026-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_operacionventa_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionventa',
            name='valor_vehiculo_usado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
