# Generated by Django 5.1.7 on 2026-06-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_titulocredito_fecha_vencimiento_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulocredito',
            name='documento_origen',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío salvo que este título reemplace a otro rechazado o en gestión.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovaciones', to='ventas.titulocredito'),
        ),
    ]
