# Generated by Django 5.1.7 on 2026-06-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_titulocredito_documento_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocobro',
            name='forma_cobro',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('pagare', 'Pagaré')], max_length=15),
        ),
    ]
