# Generated by Django 5.1.7 on 2026-06-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_id'),
        ('sucursal', '0002_alter_sucursal_id'),
        ('ventas', '0005_operacionventa_valor_vehiculo_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_titular', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='cliente_cotitular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_cotitular', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='operacionventa',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='sucursal.sucursal'),
        ),
    ]
