# Generated by Django 5.1.7 on 2026-06-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_registrocobro_forma_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocobro',
            name='forma_acreditacion_cheque',
            field=models.CharField(blank=True, choices=[('ventanilla', 'Ventanilla'), ('deposito', 'Depósito')], help_text='Solo para cheques: cómo se hizo efectivo (ventanilla o depósito).', max_length=15, null=True),
        ),
    ]
