# Generated by Django 5.1.7 on 2026-08-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_registrocobro_forma_acreditacion_cheque'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titulocredito',
            name='unique_numero_banco_emisor',
        ),
        migrations.RemoveField(
            model_name='titulocredito',
            name='documento_origen',
        ),
    ]
