# Generated by Django 5.1.7 on 2026-08-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_remove_titulocredito_unique_numero_banco_emisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='titulocredito',
            name='fecha_vencimiento_manual',
            field=models.DateField(blank=True, help_text='Solo para pagarés. Fecha de vencimiento puede ser acordada, independiente de plazos fijos.', null=True),
        ),
        migrations.CreateModel(
            name='FinanciamientoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aprobado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('numero_credito', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financiamientos', to='ventas.entidadfinanciera')),
                ('forma_pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financiamiento_externo', to='ventas.formapago')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financiamientos_externos', to='ventas.operacionventa')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('monto_aprobado__gt', 0)), name='check_monto_aprobado_positivo')],
            },
        ),
    ]
