# Generated by Django 5.1.7 on 2026-08-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_entidadfinanciera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_financiado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('tasa_interes_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monto_cuota', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('fecha_primera_cuota', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_mora', 'En Mora'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forma_pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credito_interno', to='ventas.formapago')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos_internos', to='ventas.operacionventa')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('forma_pago_cuota', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('pagare', 'Pagaré')], max_length=15, null=True)),
                ('monto_mora', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credito_interno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='ventas.creditointerno')),
            ],
        ),
        migrations.AddConstraint(
            model_name='creditointerno',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_cuotas__gt', 0)), name='check_cantidad_cuotas_positiva'),
        ),
        migrations.AddConstraint(
            model_name='creditointerno',
            constraint=models.CheckConstraint(condition=models.Q(('monto_financiado__gt', 0)), name='check_monto_financiado_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cuotacredito',
            constraint=models.UniqueConstraint(fields=('credito_interno', 'numero_cuota'), name='unique_numero_cuota_por_credito'),
        ),
        migrations.AddConstraint(
            model_name='cuotacredito',
            constraint=models.CheckConstraint(condition=models.Q(('monto_cuota__gt', 0)), name='check_monto_cuota_positivo'),
        ),
    ]
