# Generated by Django 6.0.5 on 2026-05-31 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.sucursal'),
        ),
    ]
