# Generated by Django 6.0.5 on 2026-05-31 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
        ('usuario', '0005_alter_usuario_sucursal_usuario_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursal.sucursal'),
        ),
    ]
