# Generated by Django 6.0.5 on 2026-06-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='representante_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condicion_iva',
            field=models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor Final')], max_length=30),
        ),
    ]
