# Generated by Django 4.2.16 on 2026-06-21 01:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('carroceria', models.CharField(choices=[('sedan', 'Sedán'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('camioneta', 'Camioneta'), ('furgon', 'Furgón'), ('coupe', 'Coupé'), ('familiar', 'Familiar'), ('crossover', 'Crossover'), ('minivan', 'Minivan'), ('otro', 'Otro')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_vehiculo', models.CharField(choices=[('0km', '0km'), ('usado', 'Usado')], max_length=5)),
                ('vin', models.CharField(help_text='Ingrese el número de chasis (VIN) de 17 caracteres.', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_vin', message='El VIN debe tener 17 caracteres alfanuméricos y no puede incluir las letras I, O ni Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')])),
                ('patente', models.CharField(blank=True, max_length=10, null=True)),
                ('anio', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2027)])),
                ('color', models.CharField(max_length=50)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descripcion_tecnica', models.TextField()),
                ('estado', models.CharField(choices=[('en_stock', 'En Stock'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='en_stock', max_length=20)),
                ('kilometraje', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, null=True)),
                ('combustible', models.CharField(choices=[('nafta', 'Nafta'), ('diesel', 'Diesel'), ('gnc', 'GNC'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico')], max_length=15)),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=15)),
                ('puertas', models.SmallIntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)])),
                ('motor', models.CharField(max_length=50)),
                ('traccion', models.CharField(blank=True, choices=[('delantera', 'Delantera'), ('trasera', 'Trasera'), ('4x4', '4x4')], max_length=15, null=True)),
                ('numero_serie_motor', models.CharField(max_length=100)),
                ('procedencia', models.CharField(blank=True, choices=[('compra_directa', 'Compra Directa'), ('parte_de_pago', 'Parte de Pago')], max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='sucursales.sucursaltemp')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_info_auto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('porcentaje_deduccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_tasacion_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado_cubierta', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('estado_motor', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('estado_chapa_pintura', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('estado_interior', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='inventario.taller')),
                ('usuario_autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculo_usado', to='inventario.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='TrasladoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_traslado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_traslado', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='sucursales.sucursaltemp')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='sucursales.sucursaltemp')),
                ('usuario_autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_autorizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='inventario.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='vehiculos/')),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('es_portada', models.BooleanField(default=False)),
                ('tamano_bytes', models.IntegerField(editable=False)),
                ('mime_type', models.CharField(editable=False, max_length=50)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.vehiculo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vehiculousado',
            constraint=models.CheckConstraint(check=models.Q(('porcentaje_deduccion__isnull', True), models.Q(('porcentaje_deduccion__gte', 15.0), ('porcentaje_deduccion__lte', 20.0)), _connector='OR'), name='check_porcentaje_deduccion_rango'),
        ),
        migrations.AddConstraint(
            model_name='vehiculousado',
            constraint=models.CheckConstraint(check=models.Q(('precio_tasacion_final__gt', 0)), name='check_precio_tasacion_positivo'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('patente__isnull', False)), fields=('patente',), name='unique_patente_no_nula'),
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre'), name='unique_modelo_por_marca'),
        ),
        migrations.AddConstraint(
            model_name='fotografia_vehiculo',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'orden'), name='unique_orden_por_vehiculo'),
        ),
    ]
