# Generated by Django 5.1.7 on 2026-05-29 22:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('carroceria', models.CharField(choices=[('sedan', 'Sedán'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('camioneta', 'Camioneta'), ('furgon', 'Furgón'), ('coupe', 'Coupé'), ('familiar', 'Familiar'), ('crossover', 'Crossover'), ('minivan', 'Minivan'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_vehiculo', models.CharField(choices=[('0km', '0km'), ('usado', 'Usado')], max_length=5)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('patente', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('anio', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2027)])),
                ('color', models.CharField(max_length=50)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descripcion_tecnica', models.TextField()),
                ('estado', models.CharField(choices=[('en_stock', 'En Stock'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='en_stock', max_length=20)),
                ('kilometraje', models.IntegerField(default=0)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, null=True)),
                ('combustible', models.CharField(choices=[('nafta', 'Nafta'), ('diesel', 'Diesel'), ('gnc', 'GNC'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico')], max_length=15)),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=15)),
                ('puertas', models.SmallIntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)])),
                ('motor', models.CharField(max_length=50)),
                ('traccion', models.CharField(blank=True, choices=[('delantera', 'Delantera'), ('trasera', 'Trasera'), ('4x4', '4x4')], max_length=15, null=True)),
                ('archivo', models.ImageField(upload_to='vehiculos/')),
                ('numero_serie_motor', models.CharField(max_length=100)),
                ('procedencia', models.CharField(blank=True, choices=[('compra_directa', 'Compra Directa'), ('parte_de_pago', 'Parte de Pago')], max_length=20, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='sucursales.sucursaltemp')),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='vehiculos/')),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('es_portada', models.BooleanField(default=False)),
                ('tamano_bytes', models.IntegerField()),
                ('mime_type', models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/webp', 'WEBP')], max_length=50)),
                ('orden', models.SmallIntegerField()),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.vehiculo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre'), name='unique_modelo_por_marca'),
        ),
        migrations.AddConstraint(
            model_name='fotografia_vehiculo',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'orden'), name='unique_orden_por_vehiculo'),
        ),
    ]
