# Generated by Django 5.1.7 on 2026-05-30 02:44

import django.core.validators
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia_vehiculo',
            name='archivo',
            field=models.ImageField(upload_to='vehiculos/', validators=[inventario.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='fotografia_vehiculo',
            name='mime_type',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='fotografia_vehiculo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fotografia_vehiculo',
            name='tamano_bytes',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, help_text='Ingrese el número de chasis (VIN) de 17 caracteres.', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_vin', message='El VIN debe tener 17 caracteres alfanuméricos y no puede incluir las letras I, O ni Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('patente__isnull', False)), fields=('patente',), name='unique_patente_no_nula'),
        ),
    ]
