# Generated by Django 5.1.7 on 2026-06-28 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiculo',
            name='unique_patente_no_nula',
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Formato de patente inválido. Use ABC123 (formato viejo) o AB123CD (formato Mercosur).', regex='^([A-Z]{3}\\d{3}|[A-Z]{2}\\d{3}[A-Z]{2})$')]),
        ),
    ]
