# Generated by Django 5.2.17 on 2026-08-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_vehiculo_unique_patente_no_nula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
