# Generated by Django 5.1.7 on 2026-05-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_fotografia_vehiculo_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia_vehiculo',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
