# Generated by Django 5.1.7 on 2026-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_fotografia_vehiculo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotografia_vehiculo',
            name='archivo',
            field=models.ImageField(upload_to='vehiculos/'),
        ),
    ]
