# Generated by Django 5.1.7 on 2026-05-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_vehiculo_entregado_alter_fotografia_vehiculo_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
