# Generated by Django 5.1.7 on 2026-05-31 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_vehiculo_activo'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='archivo',
        ),
        migrations.AddField(
            model_name='marca',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TrasladoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_traslado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_traslado', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='sucursales.sucursaltemp')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='sucursales.sucursaltemp')),
                ('usuario_autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_autorizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='inventario.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_info_auto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('porcentaje_deduccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_tasacion_final', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado_cubierta', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('estado_motor', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('estado_chapa_pintura', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('estado_interior', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=10, null=True)),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='inventario.taller')),
                ('usuario_autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculo_usado', to='inventario.vehiculo')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('porcentaje_deduccion__isnull', True), models.Q(('porcentaje_deduccion__gte', 15.0), ('porcentaje_deduccion__lte', 20.0)), _connector='OR'), name='check_porcentaje_deduccion_rango'), models.CheckConstraint(condition=models.Q(('precio_tasacion_final__gt', 0)), name='check_precio_tasacion_positivo')],
            },
        ),
    ]
