# Generated by Django 5.1.7 on 2026-06-01 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_taller_remove_vehiculo_archivo_marca_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(help_text='Ingrese el número de chasis (VIN) de 17 caracteres.', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_vin', message='El VIN debe tener 17 caracteres alfanuméricos y no puede incluir las letras I, O ni Q.', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
    ]
