# Generated by Django 5.1.7 on 2026-06-15 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_vehiculo_vin'),
        ('sucursal', '0002_alter_sucursal_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modelo',
            name='unique_modelo_por_marca',
        ),
        migrations.RemoveConstraint(
            model_name='vehiculousado',
            name='check_porcentaje_deduccion_rango',
        ),
        migrations.RemoveConstraint(
            model_name='vehiculousado',
            name='check_precio_tasacion_positivo',
        ),
        migrations.AlterField(
            model_name='trasladovehiculo',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrada', to='sucursal.sucursal'),
        ),
        migrations.AlterField(
            model_name='trasladovehiculo',
            name='sucursal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salida', to='sucursal.sucursal'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='sucursal.sucursal'),
        ),
    ]
