# Generated by Django 5.2.17 on 2026-09-07 00:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_vehiculo_fecha_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_obligatorio', models.BooleanField(default=True, help_text="Si es obligatorio, se exige para considerar la documentación del vehículo 'Completa' (RN-18).")),
                ('requiere_vencimiento', models.BooleanField(default=False, help_text='Marcar para documentos con validez temporal (ej. VTV, Informe de Multas).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_documento', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('en_tramite', 'En Trámite'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('fecha_recepcion', models.DateField(blank=True, help_text='Fecha de recepción del documento.', null=True)),
                ('fecha_entrega_gestor', models.DateField(blank=True, help_text='Fecha de entrega física al gestor externo (RN-19). Se completa cuando estado_documento pasa a en_tramite.', null=True)),
                ('fecha_estimada_devolucion', models.DateField(blank=True, help_text='Fecha estimada de devolución definida por el administrativo al entregar al gestor (RN-19).', null=True)),
                ('fecha_devolucion_real', models.DateField(blank=True, help_text='Fecha en que el gestor devolvió efectivamente el documento. Se completa cuando estado_documento pasa a completado.', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Aplica a documentos con validez temporal (VTV, Informe de Multas). Null para documentos sin vencimiento (título, cédula, formulario 08).', null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos_pdf/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='inventario.vehiculo')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites', to='documentacion.gestor')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_vehiculo', to='documentacion.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documentación de Vehículo',
                'verbose_name_plural': 'Documentaciones de Vehículos',
                'ordering': ['-fecha_alta'],
            },
        ),
    ]
